import logging
import os

import tensorflow as tf

from gairl.config import OUTPUTS_DIR


OUTPUT_DIRECTORY = os.path.join(OUTPUTS_DIR, 'reinforcement', 'acrobot',
                                'gairlss', '20kf50kg50kb,dqn,mlp64,64d0.75,mlp16,16d0.75')
STATE_MODEL_STR = 'mlp'
STATE_MODEL_DROPOUT = 0.75
STATE_MODEL_LAYERS = [64, 64]
REWTERM_MODEL_STR = 'mlp'
REWTERM_MODEL_DROPOUT = 0.75
REWTERM_MODEL_LAYERS = [16, 16]
RL_AGENT_STR = 'dqn'
DTYPE = tf.float64
MODEL_FREE_STEPS = 20000
MODEL_TRAINING_STEPS = 50000
MODEL_MEMORY_SIZE = 50000
MODEL_BATCH_SIZE = 256
MODEL_TEST_SIZE = 0.2
MODEL_BASED_STEPS = 100000
LOGGING_FREQUENCY = 500
LOGGING_LEVEL = logging.INFO
